name: run main.py

on:
  schedule:
    # Schedule the task for every Tuesday and Friday at 3:00 AM UTC
#    - cron: '0 3 * * 2,5'
     - cron: '*/5 * * * *'

jobs:
  run_python_task:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run your Python script
      - name: Run Python Script
        run: python main.py
